CREATE DATABASE bdnews;

CREATE TABLE CLIENTE (CODCLIENTE INT AUTO_INCREMENT,
NOME CHAR(255),
CPF CHAR(11) NOT NULL,
TELEFONE INT,
PRIMARY KEY(CODCLIENTE));

CREATE TABLE PRODUTOS (CODPRODUTO INT AUTO_INCREMENT,
DESCRICAO CHAR(255),
VALOR DOUBLE,
ESTOQUE INT,
PRIMARY KEY(CODPRODUTO));

CREATE TABLE PEDIDOS (CODPEDIDO INT AUTO_INCREMENT,
CODCLIENTE INT,
CODPRODUTO INT,
VALORVENDIDO DOUBLE,
QUANTIDADE INT,
FORMAPAGAMENTO CHAR(255),
PRIMARY KEY(CODPEDIDO));